### ISSUE TITLE
What problem does this solve that the official integration packages do not

### ISSUE THREAD

**Issue by dotnetjunkie** [existall/AspNet.Core.SimpleInjector.Integration#1]
Hi @guy-lud,

I just stumbled upon this integration package for Simple Injector and ASP.NET Core and I'm wondering what problem you are trying to solve that the official packages do not. Is there anything that the official packages can improve?

**Comment by guy-lud** [comment]
Hi @dotnetjunkie,

This is an old repository that i tried to replace the built in ASP's Ioc with SimpleInjector.
This repo is not in use anymore :)
